import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// TODO - I18n
// TODO - structure document object oriented
// TODO - project deployement system
// TODO - docker backup system (continus integration/deployment )


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
