name: deploy

on:
  push:
    branches: [ "nextjs" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: sudo docker build -t athman3/war9a .
      - name: Delete old container
        run: sudo docker rm -f war9a
      - name: Run docker container
        run: sudo docker run -d -p 3000:3000 --name war9a athman3/war9a
       