name: deploy

on:
  push:
    branches: [ "nextjs" ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_API}}
      - name: Build docker image
        run: docker build -t athman3/war9a .
      - name: Publish image to docker hub
        run: docker push athman3/war9a:latest
  
  deploy:
    needs: build
    runs-on: [kasm]
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull athman3/war9a:latest
      - name: Delete old container
        run: sudo docker rm -f war9a
      - name: Run docker container
        run: sudo docker run -d -p 3000:3000 --name war9a athman3/war9a
